// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY7mzeLeWDZIBjqgTKY-SwatxYBjThqtE',
    appId: '1:1014780408422:web:fde16b285d711b1b9133a7',
    messagingSenderId: '1014780408422',
    projectId: 'wanna-watch-later',
    authDomain: 'wanna-watch-later.firebaseapp.com',
    storageBucket: 'wanna-watch-later.appspot.com',
    measurementId: 'G-TM3GM9EE5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9AyZAz-0B9CuIPEW8PVnf1n6p_Lnwg5U',
    appId: '1:1014780408422:android:58a797f442840e689133a7',
    messagingSenderId: '1014780408422',
    projectId: 'wanna-watch-later',
    storageBucket: 'wanna-watch-later.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjNzP8aRnRpuCDJ9zxQnegHbTAO2GUjcs',
    appId: '1:1014780408422:ios:aefd96870d5aa0979133a7',
    messagingSenderId: '1014780408422',
    projectId: 'wanna-watch-later',
    storageBucket: 'wanna-watch-later.appspot.com',
    iosClientId: '1014780408422-p10mtcoast0bpvet5soe1dkvapsqujmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.wannaWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjNzP8aRnRpuCDJ9zxQnegHbTAO2GUjcs',
    appId: '1:1014780408422:ios:aefd96870d5aa0979133a7',
    messagingSenderId: '1014780408422',
    projectId: 'wanna-watch-later',
    storageBucket: 'wanna-watch-later.appspot.com',
    iosClientId: '1014780408422-p10mtcoast0bpvet5soe1dkvapsqujmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.wannaWatch',
  );
}
